# Generated by Django 2.2.5 on 2021-10-30 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='category',
        ),
        migrations.CreateModel(
            name='Categorized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_category', to='records.Category')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_record', to='records.Records')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='records_associated',
            field=models.ManyToManyField(related_name='record_assigned', through='records.Categorized', to='records.Records'),
        ),
        migrations.AddField(
            model_name='records',
            name='category_associated',
            field=models.ManyToManyField(through='records.Categorized', to='records.Category'),
        ),
    ]
