# Generated by Django 2.2.5 on 2021-10-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20211030_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
