# Generated by Django 2.2.5 on 2021-11-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_records_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='name',
            new_name='member_name',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='name',
            new_name='record_name',
        ),
    ]
