# Generated by Django 2.2.5 on 2021-11-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20211102_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='records_associated',
        ),
    ]
